### ISSUE TITLE
Unable to build on Ubuntu 18.04, kernel 4.15

### ISSUE THREAD

**Issue by gharris999** [brandon-bailey/rtl8822bu#17]
Make fails, emitting the following errors:

`make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.15.0-20-generic/build M=/home/daadmin/Drivers/rtl8822bu modules
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-20-generic'
  CC [M]  /home/daadmin/Drivers/rtl8822bu/core/rtw_cmd.o
In file included from /home/daadmin/Drivers/rtl8822bu/include/osdep_service.h:41:0,
                 from /home/daadmin/Drivers/rtl8822bu/include/drv_types.h:32,
                 from /home/daadmin/Drivers/rtl8822bu/core/rtw_cmd.c:22:
/home/daadmin/Drivers/rtl8822bu/include/osdep_service_linux.h: In function ‘_init_timer’:
/home/daadmin/Drivers/rtl8822bu/include/osdep_service_linux.h:257:8: error: ‘_timer {aka struct timer_list}’ has no member named ‘data’
  ptimer->data = (unsigned long)cntx;
        ^~
/home/daadmin/Drivers/rtl8822bu/include/osdep_service_linux.h:258:2: error: implicit declaration of function ‘init_timer’; did you mean ‘_init_timer’? [-Werror=implicit-function-declaration]
  init_timer(ptimer);
  ^~~~~~~~~~
  _init_timer
In file included from /home/daadmin/Drivers/rtl8822bu/include/drv_types.h:32:0,
                 from /home/daadmin/Drivers/rtl8822bu/core/rtw_cmd.c:22:
/home/daadmin/Drivers/rtl8822bu/include/osdep_service.h: In function ‘thread_enter’:
/home/daadmin/Drivers/rtl8822bu/include/osdep_service.h:345:2: error: implicit declaration of function ‘allow_signal’; did you mean ‘do_signal’? [-Werror=implicit-function-declaration]
  allow_signal(SIGTERM);
  ^~~~~~~~~~~~
  do_signal
/home/daadmin/Drivers/rtl8822bu/include/osdep_service.h: In function ‘flush_signals_thread’:
/home/daadmin/Drivers/rtl8822bu/include/osdep_service.h:355:6: error: implicit declaration of function ‘signal_pending’; did you mean ‘timer_pending’? [-Werror=implicit-function-declaration]
  if (signal_pending(current))
      ^~~~~~~~~~~~~~
      timer_pending
/home/daadmin/Drivers/rtl8822bu/include/osdep_service.h:356:3: error: implicit declaration of function ‘flush_signals’; did you mean ‘do_signal’? [-Werror=implicit-function-declaration]
   flush_signals(current);
   ^~~~~~~~~~~~~
   do_signal
cc1: some warnings being treated as errors
scripts/Makefile.build:332: recipe for target '/home/daadmin/Drivers/rtl8822bu/core/rtw_cmd.o' failed
make[2]: *** [/home/daadmin/Drivers/rtl8822bu/core/rtw_cmd.o] Error 1
Makefile:1552: recipe for target '_module_/home/daadmin/Drivers/rtl8822bu' failed
make[1]: *** [_module_/home/daadmin/Drivers/rtl8822bu] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-20-generic'
Makefile:1318: recipe for target 'modules' failed
make: *** [modules] Error 2
`

**Comment by dblaisdell** [comment]
The code at this [commit](https://github.com/MeissnerEffect/rtl8822bu/commit/0a23e6067f36da250686ecd775a2e97d9854d31c), was able to compile on ubuntu 18.04 with the below kernel version.

Linux ubuntu 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by aking1012** [comment]
Appears to be fixed in https://github.com/FomalhautWeisszwerg/rtl8822bu.git .  Haven't finished compiling and testing against my asus usb adapter, but it's compiling at least.  
  edit:
It's not picking up the nano card, but the USB data matches.  *shrugs*
